### ISSUE TITLE
practica 9

### ISSUE THREAD

**Issue by YulianaMorales18** [SistemasTecTlaxiaco/actividad-9-practica-de-inducci-n-matem-tica-equipo-f4#1]
[practica 3(1).pdf](https://github.com/user-attachments/files/17528880/practica.3.1.pdf)

**Comment by mae18-25** [comment]
Portada:25/25
Procedimiento:25/25
Figuras, Ilustraciones y Fotografías:25/25
Resultados y conclusiones:25/25
Total:100/100

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
